version: '3.7'

services:

  psqlcmd:
    build:
      context: ../
      dockerfile: ./builder/psqlcmd.dockerfile
      args:
        OS_VER: ubuntu:22.04
    image: ${PSQL_CLI_IMAGE:-learn-sql/psqlcmd:current}